#Chance in % of XP orb spawning after harvest done
#Range: 1 ~ 100
Chance = 100
#Amount of XP given
#Range: > 1
"XP Amount" = 2
#Enable simple harvesting and replanting with right click
"Simple Harvest" = true
#List of crops to process with their ages
"Crops List" = [
    "Block{minecraft:potatoes}[age=7]", 
    "Block{minecraft:carrots}[age=7]", 
    "Block{minecraft:wheat}[age=7]", 
    "Block{minecraft:beetroots}[age=3]", 
    "Block{minecraft:nether_wart}[age=3]",

    "Block{culturaldelights:cucumbers}[age=7]",
    "Block{culturaldelights:eggplants}[age=7]",
    "Block{culturaldelights:corn_upper}[age=3]",

    "Block{farmersdelight:onions}[age=7]",
    "Block{farmersdelight:rice_panicles}[age=3]",
    "Block{farmersdelight:cabbages}[age=7]",
    
    "Block{farmersrespite:tea_bush}[age=0]",
    "Block{farmersrespite:tea_bush}[age=1]",
    "Block{farmersrespite:tea_bush}[age=2]",
    "Block{farmersrespite:tea_bush}[age=3]",

    "Block{hexerei:sage_crop}[age=7]",

    "Block{miners_delight:cave_carrots}[age=3]",

    "Block{neapolitan:adzuki_sprouts}[age=6,flowering=true]",
    "Block{neapolitan:adzuki_sprouts}[age=6,flowering=false]",

    "Block{supplementaries:flax}[age=7,half=upper]",
]
#Curiosity Mode: sneak + right click with on block to get info in chat
Curiosity = false

